### ISSUE TITLE
How could I change the highlight item's color?

### ISSUE THREAD

**Issue by Bijiabo** [vadimdemedes/ink-select-input#23]
The highlight item's default color is blue, this color is not legibility over black terminal background color. I want to change the highlight color to be more bright.

Hope there are some solution inside this component, thanks.

**Comment by rharkov** [comment]
Any update on color change?

**Comment by vadimdemedes** [comment]
You can customize the item component via [`itemComponent`](https://github.com/vadimdemedes/ink-select-input#itemcomponent) prop. You can copy https://github.com/vadimdemedes/ink-select-input/blob/master/src/Item.tsx and start there ;)
