### ISSUE TITLE
Create an option to render horizontally 

### ISSUE THREAD

**Issue by H3RSKO** [vadimdemedes/ink-select-input#29]
Can we have the option to render ink-select-input horizontally?

In the SelectInput.js file you can change the alignment by changing line 24 and 41 to key.leftArrow and key.rightArrow respectively and  changing the flex direction to "row" on line 75.

See below for examples:

<img width="529" alt="Screen Shot 2020-08-25 at 4 38 40 PM" src="https://user-images.githubusercontent.com/34112131/91225637-f202d480-e6f1-11ea-80bc-ddef6d10ac37.png">

<img width="828" alt="Screen Shot 2020-08-25 at 4 40 22 PM" src="https://user-images.githubusercontent.com/34112131/91225742-1c549200-e6f2-11ea-8ec6-d4f44ee7cc24.png">

And it renders like this:
<img width="217" alt="Screen Shot 2020-08-25 at 4 42 05 PM" src="https://user-images.githubusercontent.com/34112131/91225689-05ae3b00-e6f2-11ea-801f-2503a58a5181.png">

**Comment by H3RSKO** [comment]
Created a package with the horizontal functionality if anyone is interested. 

https://www.npmjs.com/package/ink-select-input-horizontal

**Comment by vadimdemedes** [comment]
It's great that you published it, let's leave it separate ;)
